spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ampdatabase?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: utf-8
