spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amp_database?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8001