spring:
  datasource:
    url: jdbc:mysql://rm-cn-5yd395xr3000ae.rwlb.rds.aliyuncs.com:3306/amp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: amp_usr_1
    password: Haozequn920
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8001