spring:
  profiles:
    active: prod

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml



server:
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: utf-8

pagehelper:
  page-size-zero: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql